#!/bin/bash
# Quick reference for common GPU MODE kernel submission commands

# Set default workspace directory (can be overridden by environment variable)
WORKSPACE="${WORKSPACE:-gpu-mode}"

echo "========================================="
echo "GPU MODE Kernel Submissions - Quick Reference"
echo "========================================="
echo ""
echo "WORKSPACE DIRECTORY: ~/$WORKSPACE"
echo ""
echo "SETUP:"
echo "  # Get API URL from Discord: /get-api-url"
echo "  export POPCORN_API_URL=\"<url_from_discord>\""
echo "  cd ~/$WORKSPACE/popcorn-cli"
echo "  ./target/release/popcorn-cli register discord"
echo ""
echo "BROWSE LEADERBOARDS:"
echo "  cd ~/$WORKSPACE/popcorn-cli"
echo "  ./target/release/popcorn-cli submit"
echo ""
echo "SUBMIT A KERNEL:"
echo "  cd ~/$WORKSPACE/popcorn-cli"
echo "  ./target/release/popcorn-cli submit \\"
echo "    --gpu <GPU_MODEL> \\"
echo "    --leaderboard <leaderboard_name> \\"
echo "    --mode leaderboard \\"
echo "    ~/$WORKSPACE/submissions/my_kernel.py"
echo ""
echo "EXAMPLE SUBMISSION:"
echo "  ./target/release/popcorn-cli submit \\"
echo "    --gpu B200 \\"
echo "    --leaderboard nvfp4_gemm \\"
echo "    --mode leaderboard \\"
echo "    ~/$WORKSPACE/submissions/my_nvfp4_gemm.py"
echo ""
echo "CHECK LEADERBOARD (Discord):"
echo "  /leaderboard                    - List all leaderboards"
echo "  /leaderboard <leaderboard_name> - View specific leaderboard"
echo ""
echo "DISCORD COMMANDS:"
echo "  /get-api-url          - Get your API URL for authentication"
echo "  /leaderboard          - List all available leaderboards"
echo "  /leaderboard <name>   - View standings for a specific leaderboard"
echo ""
echo "USEFUL PATHS:"
echo "  Popcorn CLI:       ~/$WORKSPACE/popcorn-cli/target/release/popcorn-cli"
echo "  Reference Kernels: ~/$WORKSPACE/reference-kernels/problems/"
echo "  Your Submissions:  ~/$WORKSPACE/submissions/"
echo "  Config File:       ~/.popcorn.yaml"
echo ""
echo "AVAILABLE GPU MODELS (varies by leaderboard):"
echo "  - A100, H100, B200, etc."
echo "  Use the TUI to see available options for each leaderboard"
echo ""
echo "SUBMISSION MODES:"
echo "  leaderboard - Official submission (counts on leaderboard)"
echo "  dev         - Development/testing (does not count)"
echo ""
echo "RESOURCES:"
echo "  Discord:       https://discord.gg/gpumode"
echo "  GPU MODE:      https://www.gpumode.com"
echo "  YouTube:       https://www.youtube.com/@GPUMODE"
echo "  CUTLASS:       https://github.com/NVIDIA/cutlass"
echo "  Ref Kernels:   https://github.com/gpu-mode/reference-kernels"
echo "  Popcorn CLI:   https://github.com/gpu-mode/popcorn-cli"
echo ""
echo "========================================="
echo ""
echo "TIP: Set WORKSPACE environment variable to use a different directory:"
echo "  export WORKSPACE=my-custom-dir"
echo "========================================"
